baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-flex"

[params]
  favicon = "/images/favicon.ico"  # Update with your favicon path
  description = "Rapidly transforming ideas into robust digital solutions."
  customCSS = "css/custom.css"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "careers"
    name = "Careers"
    url = "/careers/"
    weight = 4
